version: "3"

services:
  loadbalance:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  api-service1:
    image: api-service
    restart: always
    ports:
      - "7081:7081"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=developement
      - PORT=7081
    volumes:
      - ./api-service/api:/home/app/api
      - ./api-service/reports:/home/app/reports
      - ./api-service/uploads:/home/app/uploads
      - ./api-service/app.py:/home/app/app.py
      - ./api-service/database:/home/app/database
      - ./api-service/utils.py:/home/app/utils.py

  api-service2:
    image: api-service
    restart: always
    ports:
      - "7082:7082"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=developement
      - PORT=7082
    volumes:
      - ./api-service/api:/home/app/api
      - ./api-service/reports:/home/app/reports
      - ./api-service/uploads:/home/app/uploads
      - ./api-service/app.py:/home/app/app.py
      - ./api-service/database:/home/app/database
      - ./api-service/utils.py:/home/app/utils.py

  dashboard-nextjs:
    image: dashboard-nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    volumes:
      - ./dashboard-nextjs/components:/app/components
      - ./dashboard-nextjs/pages:/app/pages
      - ./dashboard-nextjs/public:/app/public
      - ./dashboard-nextjs/utils:/app/utils
