version: "3"

services:
  loadbalance:
    image: haproxy
    ports:
      - "8981:8981"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  api-service1:
    image: api-service
    restart: always
    ports:
      - "7081:7081"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=developement
      - PORT=7081
    volumes:
      - ./api-service/uploads:/home/app/uploads

  dashboard-nextjs:
    image: dashboard-nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
