version: "3"

services:
  loadbalance:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  # nginx_lb:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx:/etc/nginx/
  #   ports:
  #     - "8080:8080"
  #     - "3000:3000"

  pg:
    image: eg_postgresql
    restart: always

  api-service1:
    image: api-service
    restart: always
    ports:
      - "7081:7081"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=developement
      - PORT=7081

  api-service2:
    image: api-service
    restart: always
    ports:
      - "7082:7082"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=developement
      - PORT=7082

  api-service3:
    image: api-service
    restart: always
    ports:
      - "7083:7083"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=developement
      - PORT=7083

  api-service4:
    image: api-service
    ports:
      - "7084:7084"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=developement
      - PORT=7084

  # app-dashboard:
  #   image: app-dashboard
  #   restart: always
