version: "3"

services:
  api-service:
    image: api-service
    restart: always
    ports:
      - "7980:7980"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=developement
      - PORT=7980
    volumes:
      - ./api-service/uploads:/home/app/uploads

  app-dashboard:
    image: app-dashboard
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
