version: "3"

services:
  loadbalance:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    logging:
      options:
        max-size: 50m

  api-service1:
    image: api-service
    restart: always
    ports:
      - "7081:7081"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=developement
      - PORT=7081
    volumes:
      - ./api-service/api:/home/app/api
      - ./api-service/reports:/home/app/reports
      - ./api-service/uploads:/home/app/uploads
      - ./api-service/app.py:/home/app/app.py
      - ./api-service/database:/home/app/database
      - ./api-service/utils.py:/home/app/utils.py
    logging:
      options:
        max-size: 50m

  api-service2:
    image: api-service
    restart: always
    ports:
      - "7082:7082"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=developement
      - PORT=7082
    volumes:
      - ./api-service/api:/home/app/api
      - ./api-service/reports:/home/app/reports
      - ./api-service/uploads:/home/app/uploads
      - ./api-service/app.py:/home/app/app.py
      - ./api-service/database.py:/home/app/database.py
      - ./api-service/utils.py:/home/app/utils.py
    logging:
      options:
        max-size: 50m

  # dashboard-nextjs:
  #   image: dashboard-nextjs
  #   restart: always
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   stdin_open: true
  #   volumes:
  #     - ./dashboard-nextjs:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - "3000:3000"
  #   logging:
  #     options:
  #       max-size: 50m

  # dashboard:
  #   image: dashboard
  #   restart: always
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   stdin_open: true
  #   volumes:
  #     - ./dashboard:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   logging:
  #     options:
  #       max-size: 50m
