import { Box } from "@chakra-ui/layout";
import Head from "next/head";
import LoginFrom from "../components/LoginFrom";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>MNC GMAC</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <Box m="5">
          <LoginFrom />
        </Box>
      </main>
    </div>
  );
}
